### ISSUE TITLE
Can't Post News to Blender.Today

### ISSUE THREAD

**Issue by ryankingart** [armadillica/dillo#145] opened 2021-01-30 23:39 UTC
Hello,
I'm having an issue using the Blender.Today Website. I create Blender Tutorials, and I like sharing them on Blender.Today. Up until a few days ago, everything was working fine, but just recently, When I click on the, Submit Link, button, on the top right, the screen goes a blue tint, and nothing comes up. If I click on the dropdown menu, and click on, Write a Post, it Says: 404 Not Found. Do you know why this is happening? How can I post news to Blender.Today?
Thanks!
Ryan King,

![Issue 1](https://user-images.githubusercontent.com/52793051/106370686-4cdbd000-6311-11eb-9de5-af6ed6b65d8f.png)

![Issue 2](https://user-images.githubusercontent.com/52793051/106370674-3766a600-6311-11eb-8985-00b216f24932.png)

**Comment by venomgfx** [comment] 2021-01-31 04:34
Thanks for reporting. I can't reproduce the issue here, is it still happening? Sometimes under heavy server load this could happen. What's your username? Maybe checking the logs we get a clue.

**Comment by ryankingart** [comment] 2021-01-31 05:29
Hello Pablo. Thanks for your reply. Yes, its still happening, and has been for a few days now. I have tried logging out and logging back in, as well as trying it on Firefox, and Chrome, but I still have the same issue. How can I check the log your talking about?
Thanks, Ryan 

@venomgfx

**Comment by ryankingart** [comment] 2021-01-31 23:18
@venomgfx I just tried it again and it works now. Hopefully it will continue to work. Did you do something to fix it? Or maybe it was just a glitch that was fixed on its own?
Anyways, thanks Pablo!
Ryan,

**Comment by venomgfx** [comment] 2021-01-31 23:57
Yes I gave it a little nudge but the site is showing its age already. Luckily we are working on a new version of the entire system. It will be a couple months at least but it's on its way.

I will close this for now, feel free to open a new ticket if necessary.

**Closed by venomgfx** 2021-01-31 23:57 UTC
