### ISSUE TITLE
Display of HTML tags in the text of the content of the publications

### ISSUE THREAD

**Issue by Martincho84** [armadillica/dillo#59] opened 2018-01-17 17:13 UTC
When entering my profile or the profile of another user and viewing a publication, the HTML tags are displayed as the image shows. As a result, the sets are not displayed as **strong**, _em_, etc.

![screenshot_1](https://user-images.githubusercontent.com/35337938/35056271-1d5f370e-fb90-11e7-825a-e2a35cfa29ad.jpg)

**Comment by ChameleonScales** [comment] 2018-01-17 18:35
isn't this a duplicate of issue #51 ?

**Closed** 2018-01-17 19:41 UTC
